ukm_designbundle:
    resource: "@UKMDesignBundle/Resources/config/routing.yml"
    prefix:   /

uk_mtv:
    resource: "@UKMtvBundle/Resources/config/routing.yml"
    prefix:   /

ukm_ntvgui:
    resource: "@UKMNtvguiBundle/Resources/config/routing.yml"
    prefix:   /

