twig:
    paths:
        '%kernel.project_dir%/vendor/ukmnorge/design/Resources/views/UKMDesign': UKMDesign
    globals:
      UKMDesign: '@App\UKMNorge\UKMDesign\Services\UKMDesign'
      UKM_HOSTNAME: 'ukm.dev'